### ISSUE TITLE
There are still/again a whole bunch of folders on /cortalg without the correct group permissions. This means I cannot make a back to VS02. Please fix this!

### ISSUE THREAD

**Issue by pcklink** [VisionandCognition/NHP-BIDS#17]
These are the folders in  /project/cortalg/NHP-BIDS/derivatives/modelfit:
drwx--S---  7 waghmare cortalg  102 May 16 19:32 kw-danny-curvetracing-modelfit-20190515
drwx--S---  7 waghmare cortalg  102 May 28 12:48 kw-danny-curvetracing-modelfit-20190516
drwx--S---  7 waghmare cortalg  102 May 28 13:14 kw-danny-curvetracing-modelfit-20190523
drwx--S---  7 waghmare cortalg  102 Jun  2 03:38 kw-danny-curvetracing-modelfit-20190529
drwx--S---  7 waghmare cortalg  102 May 28 16:49 kw-danny-curvetracing-modelfit-multi-201905
drwx--S---  7 waghmare cortalg  102 Jun  2 07:49 kw-danny-curvetracing-modelfit-multi-2019MAY
drwx--S---  7 waghmare cortalg  102 Jun 17 20:43 kw-danny-curvetracing-modelfit-multi-2019MAY-e

**Comment by kanishkatks** [comment]
DONE!
