### ISSUE TITLE
remove code/bids_templates.py

### ISSUE THREAD

**Issue by mekman** [VisionandCognition/NHP-BIDS#2]
AFAIK this is not necessary to have this as all the information can be provided via the csv

**Comment by williford** [comment]
Yes, bids_templates.py should be removed (once there is no other code relying on it).

**Comment by pcklink** [comment]
took it out, but I'm working on some other changes before it gets fully implemented.

**Comment by pcklink** [comment]
No longer required. Everything works with the (NEW) csv-file now.
