### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by pcklink** [VisionandCognition/NHP-BIDS#25]
@kanishkatks can you add group rw permissions for:

chmod g+rw  ~/cortalg/NHP-BIDS/derivatives/featpreproc/motion_corrected/sub-danny/ses-20190416/func/sub-danny_ses-20190416_task-curvetracinginccentral_run-01_bold_res-1x1x1_preproc_mc.nii.gz

chmod g+rw ~/cortalg/NHP-BIDS/sub-eddy/ses-20180228

I cannot sync it with our non-cluster data storage.

**Comment by kanishkatks** [comment]
Done!

**Comment by pcklink** [comment]
My bad, should be done recursively

chmod -r g+rw ~/cortalg/NHP-BIDS/sub-eddy/ses-20180228

**Comment by nhpatscnin** [comment]
I (kanishk) am getting permission error too. @pcklink you're the owner.

**Comment by pcklink** [comment]
Fixed
