### ISSUE TITLE
DOC: document which software versions are required, freesurfer, fsl, ants..

### ISSUE THREAD

**Issue by mekman** [VisionandCognition/NHP-BIDS#3]
and add to README

**Comment by pcklink** [comment]
[should probably keep my replies/comments/questions in the thread] How did you determine the minimally required software versions (>=) for the readme? I'm using AFNI 17.2.10 (Linux) and 17.2.08 (mac), and ants v2.2.0, but I don't know whether older versions would work just as well...

**Comment by mekman** [comment]
Good question. For now it's the minimal version that worked. I am planning to test this more systematically in the upcoming weeks. I opened this issue to remind myself.. :-)

**Comment by pcklink** [comment]
Don't know if it is worth going through extensive version checking. We can can just mention that these are the *tested* minimal requirements.
